theme: jekyll-theme-minimal
show_downloads: false
google_analytics: UA-131573516-1
permalink: pretty

collections:
  events:
    output: true
  topics:
    output: true
    sort_by: order

url: "https://actd.nl"

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
